name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release API
    runs-on: ubuntu-latest

    # job steps
    steps:
      # Prepare source code
      # https://github.com/marketplace/actions/checkout
      - name: Clone repo
        uses: actions/checkout@v2

      # Setup of environment
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish locus-api-core
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}

        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # So if we split on '/' and take the 3rd value, we can get the release name.
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -PAPI_VERSION=${NEW_VERSION} locus-api-core:publishReleasePublicationToGitHubPackagesRepository

      - name: Publish locus-api-android
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}

        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # So if we split on '/' and take the 3rd value, we can get the release name.
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -PAPI_VERSION=${NEW_VERSION} locus-api-android:publishReleasePublicationToGitHubPackagesRepository
