name: Release

on:
  push:
    tags:
      - '*'

env:
  ANDROID_SIGN_DEBUG: ${{ secrets.ANDROID_SIGN_DEBUG }}
  ANDROID_SIGN_RELEASE: ${{ secrets.ANDROID_SIGN_RELEASE }}

jobs:
  build:
    name: Release API
    runs-on: ubuntu-latest

    # job steps
    steps:
      # Prepare source code
      # https://github.com/marketplace/actions/checkout
      - name: Clone repo
        uses: actions/checkout@v2

      # Setup of environment
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Base64 decodes and pipes the GPG key content into the secret file
      - name: Prepare environment
        env:
          GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        run: |
          git fetch --unshallow
          sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"

      # Set locale environment
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

      # Public Locus API - core
      - name: Publish `locus-api-core`
        run: ./gradlew :locus-api-core:clean :locus-api-core:publishReleasePublicationToMavencentralRepository

      # Publish Locus API - Android
      - name: Publish `locus-api-android`
        run: ./gradlew :locus-api-android:clean :locus-api-android:assembleRelease :locus-api-android:publishReleasePublicationToMavencentralRepository

      # Runs upload, and then closes & releases the repository
      - name: Releaes repository
        run: ./gradlew closeAndReleaseRepository
